import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sensei = localFont({
    src: "./fonts/Sensei-Medium.ttf",
    weight: "100",
    variable: "--font-sensei",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sensei.variable} ${sensei.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
